### ISSUE TITLE
Simple README instructions

### ISSUE THREAD

**Issue by shadesoflight** [signalwerk/colorLab#2]
Hey, it was easy enough to figure out from the code the following:

Install:
1) bower install --save signalwerk/colorLab
2) include colorLab.js in your template

DeltaE of two colors:
1) var color1 = new colorLab('CIELAB', [red, green, blue])
2) var color2 = new colorLab('CIELAB', [red, green, blue])
3) color1.CIEDE2000(color2); // this tells you the DeltaE, or perceptible color difference, between color1 and color2

**Comment by signalwerk** [comment]
@shadesoflight Thanks a lot for your example. The lib was built a bit in a hurry. Therefor it's also lacking of some nice examples ._. But thanks to you we have now something in the readme ^.^
II added your instructions to the readme (11b051656f52c5fd9fe0ac84657766fb3991c843) and gave you also credits (3c176e0104650250e7401d95c5cdd0f19564bb5d). Thanks a lot and if you do something cool with it or have a pull request; just let me know.
